

###
GET http://localhost:3000/api/users/allUsers
###

GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y2MjBjNWYzM2ZmN2NkMWRlMWJjODMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0MTgzNDkzLCJleHAiOjE3NDQxOTA2OTN9.zV1WGVVk59HI7_WkUt7zcYHd-YOHEo1qdB5ETucf3Lw
###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "email": "nicolaila@gmail.com",
  "password": "password"
}
###
PUT http://localhost:3000/api/users/validation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y2MjBjNWYzM2ZmN2NkMWRlMWJjODMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0MTgzNDkzLCJleHAiOjE3NDQxOTA2OTN9.zV1WGVVk59HI7_WkUt7zcYHd-YOHEo1qdB5ETucf3Lw

{
  "code":898955
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "nicolaila@gmail.com",
  "password": "password"
}

###
PUT http://localhost:3000/api/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYWE2Mjk5N2UyYmRlYjc2OTc2OTUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDMyMjkwLCJleHAiOjE3NDM0Mzk0OTB9.ypZRam9O0H92dS3OH9SIKR-UodDWFpiNoo-Aueg9F28

{
  "email": "nicolaila@gmail.com",
  "name": "Nicolas",
  "surnames": "Calvo",
  "nif": "40000000W",
  "autonomo":true
}
###
PATCH http://localhost:3000/api/users/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYWE2Mjk5N2UyYmRlYjc2OTc2OTUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDMyMjkwLCJleHAiOjE3NDM0Mzk0OTB9.ypZRam9O0H92dS3OH9SIKR-UodDWFpiNoo-Aueg9F28

{
  "company": {
    "name": "Servitop, SL.",
    "cif": "BXXXXXXXX",
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}
###
PATCH http://localhost:3000/api/users/logo HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYWE2Mjk5N2UyYmRlYjc2OTc2OTUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDMyMjkwLCJleHAiOjE3NDM0Mzk0OTB9.ypZRam9O0H92dS3OH9SIKR-UodDWFpiNoo-Aueg9F28

--boundary123
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/png

< ./image.png
--boundary123--

###
POST http://localhost:3000/api/mail
Content-Type: application/json

{
  "subject": "Asunto del correo",
  "text": "Contenido del mensaje",
  "to": "eduardoyc04@gmail.com",
  "from": "eduardoyc04@gmail.com"
}
###
DELETE http://localhost:3000/api/users?soft=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RjNTQ4ZmFkMzJlZjIzMzAzZDQwOWYiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyNDkyODE1LCJleHAiOjE3NDI1MDAwMTV9.5UFuFMjisZ0gcki2XBRjLl04QGDu8mHI3nQieRiQ2Ek
###

GET http://localhost:3000/api/users/verify
Content-Type: application/json

{
  "email":"nicolaila@gmail.com" 
}

###
POST http://localhost:3000/api/users/validation
Content-Type: application/json

{
  "email":"nicolaila@gmail.com",
  "code":777255
}

###
PATCH http://localhost:3000/api/users/cambiarPassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYWE2Mjk5N2UyYmRlYjc2OTc2OTUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDMyMjkwLCJleHAiOjE3NDM0Mzk0OTB9.ypZRam9O0H92dS3OH9SIKR-UodDWFpiNoo-Aueg9F28

{
  "email":"nicolaila@gmail.com",
  "password":"NewPassword"
}

###
PATCH http://localhost:3000/api/users/address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2VhYWE2Mjk5N2UyYmRlYjc2OTc2OTUiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzNDMyMjkwLCJleHAiOjE3NDM0Mzk0OTB9.ypZRam9O0H92dS3OH9SIKR-UodDWFpiNoo-Aueg9F28

{
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}
###
POST http://localhost:3000/api/users/invite
Content-Type: application/json

{
  "name": "Manuel",
  "surnames": "Pérez Gómez",
  "email": "guest@gmail.com",
  "password":"password",
  "role":"guest",
  "company": {
    "name": "Servitop, SL.",
    "cif": "BXXXXXXXX",
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}

###
POST http://localhost:3000/api/client
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODA4OWIwZjlhZjk2ZjkwMTZkZGM2MTIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1Mzk0NDQ3LCJleHAiOjE3NDU0MDE2NDd9.iD-IbauaBYa0E6kBdO20NwqoMPvhwY_d-cY4QKjFSCk

{
  "name": "ACS2",
  "cif": "D52921210",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}

###
GET http://localhost:3000/api/client/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyMmJmOTViYTVjODZkNTAzNTQ2ZjMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTcyNzk0LCJleHAiOjE3NDQ5Nzk5OTR9.ETdVXmlwxT0Smz9KW4iUtp_c6pboYreDMa5LNEFMfd8

###
GET http://localhost:3000/api/client/68089b2b9af96f9016ddc616
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODA4OWIwZjlhZjk2ZjkwMTZkZGM2MTIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1Mzk0NDQ3LCJleHAiOjE3NDU0MDE2NDd9.iD-IbauaBYa0E6kBdO20NwqoMPvhwY_d-cY4QKjFSCk

###
DELETE http://localhost:3000/api/client/68089b2b9af96f9016ddc616
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyMmJmOTViYTVjODZkNTAzNTQ2ZjMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTcyNzk0LCJleHAiOjE3NDQ5Nzk5OTR9.ETdVXmlwxT0Smz9KW4iUtp_c6pboYreDMa5LNEFMfd8

###
DELETE http://localhost:3000/api/client/archive/68022c082f41b78e03477c99
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyMmJmOTViYTVjODZkNTAzNTQ2ZjMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTcyNzk0LCJleHAiOjE3NDQ5Nzk5OTR9.ETdVXmlwxT0Smz9KW4iUtp_c6pboYreDMa5LNEFMfd8

###
GET http://localhost:3000/api/client/archive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyMmJmOTViYTVjODZkNTAzNTQ2ZjMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTcyNzk0LCJleHAiOjE3NDQ5Nzk5OTR9.ETdVXmlwxT0Smz9KW4iUtp_c6pboYreDMa5LNEFMfd8

###
PATCH http://localhost:3000/api/client/restore/680154dc92ac54a5a664c2e2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyMmJmOTViYTVjODZkNTAzNTQ2ZjMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTcyNzk0LCJleHAiOjE3NDQ5Nzk5OTR9.ETdVXmlwxT0Smz9KW4iUtp_c6pboYreDMa5LNEFMfd8

###
PUT http://localhost:3000/api/client/680154d092ac54a5a664c2de
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyMmJmOTViYTVjODZkNTAzNTQ2ZjMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTcyNzk0LCJleHAiOjE3NDQ5Nzk5OTR9.ETdVXmlwxT0Smz9KW4iUtp_c6pboYreDMa5LNEFMfd8

{
  "name": "ACS1",
  "cif": "D52921213",
  "address": {
    "street": "EDUARDO I",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}

###
POST http://localhost:3000/api/projects/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODA4OWIwZjlhZjk2ZjkwMTZkZGM2MTIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ1Mzk0NDQ3LCJleHAiOjE3NDU0MDE2NDd9.iD-IbauaBYa0E6kBdO20NwqoMPvhwY_d-cY4QKjFSCk

{
  "name": "Nombre del proyecto",
  "projectCode": "Identificador de proyect",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  },
  "code": "Código interno del proyecto",
  "clientId": "68089b2b9af96f9016ddc616"
}
###

GET http://localhost:3000/api/projects/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyODQ1MjYyZDE4YmNhNTE5YTQzOWIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTk1NDEwLCJleHAiOjE3NDUwMDI2MTB9.13RbpFZYFfP82jpFuxAQKL427as8H7khTyNb5_mJeH0
###

GET http://localhost:3000/api/projects/6802884a5010fd6f5815b448
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyODQ1MjYyZDE4YmNhNTE5YTQzOWIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTk1NDEwLCJleHAiOjE3NDUwMDI2MTB9.13RbpFZYFfP82jpFuxAQKL427as8H7khTyNb5_mJeH0

###
DELETE http://localhost:3000/api/projects/6802884a5010fd6f5815b448
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyODQ1MjYyZDE4YmNhNTE5YTQzOWIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTk1NDEwLCJleHAiOjE3NDUwMDI2MTB9.13RbpFZYFfP82jpFuxAQKL427as8H7khTyNb5_mJeH0

###
DELETE http://localhost:3000/api/projects/archive/6802871c4ba9472f7c696850
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyODQ1MjYyZDE4YmNhNTE5YTQzOWIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTk1NDEwLCJleHAiOjE3NDUwMDI2MTB9.13RbpFZYFfP82jpFuxAQKL427as8H7khTyNb5_mJeH0

###
GET http://localhost:3000/api/projects/archive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyODQ1MjYyZDE4YmNhNTE5YTQzOWIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTk1NDEwLCJleHAiOjE3NDUwMDI2MTB9.13RbpFZYFfP82jpFuxAQKL427as8H7khTyNb5_mJeH0

###
PATCH http://localhost:3000/api/projects/restore/6802871c4ba9472f7c696851
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyODQ1MjYyZDE4YmNhNTE5YTQzOWIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTk1NDEwLCJleHAiOjE3NDUwMDI2MTB9.13RbpFZYFfP82jpFuxAQKL427as8H7khTyNb5_mJeH0

###
PUT http://localhost:3000/api/projects/6802871c4ba9472f7c696850
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODAyODQ1MjYyZDE4YmNhNTE5YTQzOWIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQ0OTk1NDEwLCJleHAiOjE3NDUwMDI2MTB9.13RbpFZYFfP82jpFuxAQKL427as8H7khTyNb5_mJeH0

{
  "name": "Pardo Project",
  "projectCode": "Identificador de proyecto",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  },
  "code": "Código interno del proyecto",
  "clientId": "6802847062d18bca519a439f"
}

###
GET http://localhost:3000/api/pdf