GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Q5OGMwOGFmYmU1ZDk0MjJjOWQwNDMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyMzEwNDA4LCJleHAiOjE3NDIzMTc2MDh9.RKjEpC8ahtLtk_WVypSAdRAmunSy3mFg9PNJz1Enj-M
###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "email": "pardo@gmail.com",
  "password": "password"
}
###
PUT http://localhost:3000/api/users/validation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhZGZkODAzNzEwM2E4ZGEwYmY5ZTgiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyMzk3NDAwLCJleHAiOjE3NDI0MDQ2MDB9.VduBwZ7CsmfbcqttvdrF1aqX_6VYExq37uJn9VttGJY

{
  "code":140795
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "nicolaila@gmail.com",
  "password": "password"
}

###
PUT http://localhost:3000/api/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhZTRkMzMwNjAwNDhmZTRhOGY1MzkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyMzk4Njc1LCJleHAiOjE3NDI0MDU4NzV9.OY8Td__4bZlzeBEQyZGalNuOA_fX3daFyubQXc7GRKc

{
  "email": "pardo@gmail.com",
  "name": "Nicolas",
  "surnames": "Calvo",
  "nif": "40000000W"
}
###
PATCH http://localhost:3000/api/users/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RhZTRkMzMwNjAwNDhmZTRhOGY1MzkiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQyMzk4Njc1LCJleHAiOjE3NDI0MDU4NzV9.OY8Td__4bZlzeBEQyZGalNuOA_fX3daFyubQXc7GRKc

{
  "company": {
    "name": "Servitop, SL.",
    "cif": "BXXXXXXXX",
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}


###
POST http://localhost:3000/api/mail
Content-Type: application/json

{
  "subject": "Asunto del correo",
  "text": "Contenido del mensaje",
  "to": "eduardoyc04@gmail.com",
  "from": "eduardoyc04@gmail.com"
}